### ISSUE TITLE
Protobuf message contract

### ISSUE THREAD

**Issue by sunkararp** [vesoft-inc/nebula-studio#63]
We wanted to use .net core 6.0 gRpc client to interact with Nebula graph.
Questions:
- Is there a nebula graph  .net client library?
- If not, can someone point where can I find Nebula graph protobuf contract message, we wanted to use it write our own library?

**Comment by wey-gu** [comment]
Dear @sunkararp,

Welcome to nebula community~~

Nebula GraphD now can only speak [facebook thrift](https://github.com/facebook/fbthrift) rather than gRPC. There is not yet .net client out there but [a team in nebula hackathon ](https://github.com/vesoft-inc/nebula-community/blob/master/hackathon/hackathon-2021/teams.md#nullreferenceexception)is working on this :).

Before .net client is ready, you could consider talk to nebula graph in .net with HTTP through [nebula-http-gateway](https://github.com/vesoft-inc/nebula-http-gateway) :).

BR//Wey

**Comment by sunkararp** [comment]
We tried nebula-http-gateway, here are the issues we found...
- We followed [These docs to use http-gateway](https://github.com/vesoft-inc/nebula-http-gateway)
- Getting this error 'connection refused for lack of session'
- We are setting 'nsid' cookie returned through '/api-nebula/db/connect'

**Comment by wey-gu** [comment]
Dear @sunkararp 
sorry for its confusing, the docs in readme changed in master build for an unreleased upcoming version.

Could you follow the README [last tagged version](https://github.com/vesoft-inc/nebula-http-gateway/tree/v2.1.1)(which is nsid not common-nsid)?

```
curl -X POST -H "Cookie: SameSite=None; nsid=6573259f9fac8f318894112f907e151a" -d '{"gql": "show spaces;"}' http://127.0.0.1:8080/api/db/exec
{
  "code": 0,
  "data": {
    "headers": [],
    "tables": [],
    "timeCost": 0
  },
  "message": ""
```

**Comment by sunkararp** [comment]
Thanks @wey-gu for the reply.

- Now '/api-nebula/db/connect' is working
- We are able to call /api-nebula/db/exec with {"gql": "show spaces;"} payload

We now wanted to call Import API (/api-nebula/task/import), to bulk ingest Vertices and Edges.
Can you let us know sample configBody JSON body schema?

**Comment by wey-gu** [comment]
@sunkararp

`Import API` is actually simply calling https://github.com/vesoft-inc/nebula-importer as a lib from http-gateway.

Please take a look into https://github.com/vesoft-inc/nebula-importer 's guide to make more sense of it: the bulk information it self is not in the body but in a file path that gateway can access.

If that is not what you want, you could also create long ngql body with exec API instead. Please note nGQL like insert support BULK, thus we should put bulk vertex insert in one line instead of multiple lines.

**Comment by wey-gu** [comment]
BTW, you can actually try https://github.com/shyboylpf/nebula-net , they presented in the nebula hackathon yesterday!

**Comment by sunkararp** [comment]
We tried to use ttps://github.com/shyboylpf/nebula-net, stuck with getting below...

SemanticError: The maximum number of statements allowed has been exceeded

**Comment by wey-gu** [comment]
> We tried to use ttps://github.com/shyboylpf/nebula-net, stuck with getting below...
> 
> SemanticError: The maximum number of statements allowed has been exceeded

I saw your issue https://github.com/shyboylpf/nebula-net/issues/10 , responded there.
